export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_CART_START = 'GET_CART_START';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';

export const CREATE_CART_START = 'CREATE_CART_START';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL';

export const PATCH_ADD_CART_START = 'PATCH_ADD_CART_START';
export const PATCH_ADD_CART_SUCCESS = 'PATCH_ADD_CART_SUCCESS';
export const PATCH_ADD_CART_FAIL = 'PATCH_ADD_CART_FAIL';

export const PATCH_REMOVE_CART_START = 'PATCH_REMOVE_CART_START';
export const PATCH_REMOVE_CART_SUCCESS = 'PATCH_REMOVE_CART_SUCCESS';
export const PATCH_REMOVE_CART_FAIL = 'PATCH_REMOVE_CART_FAIL';

export const DELETE_CART_START = 'DELETE_CART_START';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL';